# Generated by Django 2.0.5 on 2018-05-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_txns", models.IntegerField(default=0)),
                ("source", models.CharField(max_length=200)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawTxn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField()),
                ("external_id", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("sum", models.FloatField(default=0)),
                ("date", models.DateField(verbose_name="Transaction Date")),
                (
                    "import_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ImportMetadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Txn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField()),
                ("external_id", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("sum", models.FloatField(default=0)),
                ("date", models.DateField(verbose_name="Transaction Date")),
                ("comment", models.CharField(blank=True, max_length=1000)),
                (
                    "raw_txn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.RawTxn"
                    ),
                ),
            ],
        ),
    ]
