# Generated by Django 2.0.5 on 2018-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="importmetadata",
            name="file",
            field=models.FileField(default="imports/None.xls", upload_to="imports"),
        )
    ]
