# Generated by Django 2.0.5 on 2018-05-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="importmetadata", name="import_id"),
        migrations.RemoveField(model_name="rawtxn", name="raw_txn_id"),
    ]
