# Generated by Django 2.0.5 on 2018-05-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20180526_1527")]

    operations = [
        migrations.RemoveField(model_name="importmetadata", name="user_id"),
        migrations.AlterField(
            model_name="importmetadata",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
